// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zganktkemdiktjrxcgsc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpnYW5rdGtlbWRpa3RqcnhjZ3NjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MDMwMDYsImV4cCI6MjA2MDM3OTAwNn0.jI-kW0MaPEfr-FgYTZIDMErq8N2TW060Js8vZD821OE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);